import DefaultTheme from './default';

export default DefaultTheme.extend({
  table: 'table table-striped table-bordered table-condensed',
  globalFilterWrapper: 'pull-left',
  columnsDropdownWrapper: 'pull-right columns-dropdown',
  columnsDropdownButtonWrapper: 'btn-group',
  columnsDropdown: 'dropdown-menu pull-right',
  footerSummaryNumericPagination: 'col-md-4 col-sm-4 col-xs-4',
  footerSummaryDefaultPagination: 'col-md-5 col-sm-5 col-xs-5',
  pageSizeWrapper: 'col-md-2 col-sm-2 col-xs-2',
  pageSizeSelectWrapper: 'pull-right',
  paginationWrapperNumeric: 'col-md-6 col-sm-6 col-xs-6',
  paginationWrapperDefault: 'col-md-5 col-sm-5 col-xs-5',
  buttonDefault: 'btn btn-default',
  input: 'form-control',
  tfooterWrapper: 'table-footer clearfix',
  clearFilterIcon: 'glyphicon glyphicon-remove-sign form-control-feedback',
  clearAllFiltersIcon: 'glyphicon glyphicon-remove-circle',
  'sort-asc': 'glyphicon glyphicon-triangle-top',
  'sort-desc': 'glyphicon glyphicon-triangle-bottom',
  'column-visible': 'glyphicon glyphicon-check',
  'column-hidden': 'glyphicon glyphicon-unchecked',
  'nav-first': 'glyphicon glyphicon-chevron-left',
  'nav-prev': 'glyphicon glyphicon-menu-left',
  'nav-next': 'glyphicon glyphicon-menu-right',
  'nav-last': 'glyphicon glyphicon-chevron-right',
  'caret': 'caret',
  'expand-row': 'glyphicon glyphicon-plus',
  'expand-all-rows': 'glyphicon glyphicon-plus',
  'collapse-row': 'glyphicon glyphicon-minus',
  'collapse-all-rows': 'glyphicon glyphicon-minus',
  'select-all-rows': 'glyphicon glyphicon-check',
  'deselect-all-rows': 'glyphicon glyphicon-unchecked',
  'select-row': 'glyphicon glyphicon-check',
  'deselect-row': 'glyphicon glyphicon-unchecked'
});