import ModelsTableComponent from 'ember-models-table/components/models-table';
import ModelsTableServerPaginated from 'ember-models-table/components/models-table-server-paginated';
import PlainHtmlColumnsDropdown from 'ember-models-table/components/models-table/themes/plain-html/columns-dropdown';
import PlaintHtmlGlobalFilter from 'ember-models-table/components/models-table/themes/plain-html/global-filter';
import PlainHtmlRowFilteringCell from 'ember-models-table/components/models-table/themes/plain-html/row-filtering-cell';
import PlainHtmlSummary from 'ember-models-table/components/models-table/themes/plain-html/summary';
import EmberBootstrapV5ColumnsDropdown from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/columns-dropdown';
import EmberBootstrapV5DataGroupBySelect from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/data-group-by-select';
import EmberBootstrapV5GlobalFilter from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/global-filter';
import EmberBootstrapV5PageSizeSelect from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/page-size-select';
import EmberBootstrapV5PaginationNumeric from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/pagination-numeric';
import EmberBootstrapV5PaginationSimple from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/pagination-simple';
import EmberBootstrapV5RowFilteringCell from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/row-filtering-cell';
import EmberBootstrapV5Summary from 'ember-models-table/components/models-table/themes/ember-bootstrap-v5/summary';
import EmberBootstrapV4ColumnsDropdown from 'ember-models-table/components/models-table/themes/ember-bootstrap-v4/columns-dropdown';
import EmberBootstrapV4DataGroupBySelect from 'ember-models-table/components/models-table/themes/ember-bootstrap-v4/data-group-by-select';
import EmberBootstrapV4GlobalFilter from 'ember-models-table/components/models-table/themes/ember-bootstrap-v4/global-filter';
import EmberBootstrapV4RowFilteringCell from 'ember-models-table/components/models-table/themes/ember-bootstrap-v4/row-filtering-cell';
import EmberBootstrapV4Summary from 'ember-models-table/components/models-table/themes/ember-bootstrap-v4/summary';
import Bootstrap3RowSelectAllCheckbox from 'ember-models-table/components/models-table/themes/bootstrap3/row-select-all-checkbox';
import Bootstrap4ColumnsDropdown from 'ember-models-table/components/models-table/themes/bootstrap4/columns-dropdown';
import Bootstrap4DataGroupBySelect from 'ember-models-table/components/models-table/themes/bootstrap4/data-group-by-select';
import Bootstrap4GlobalFilter from 'ember-models-table/components/models-table/themes/bootstrap4/global-filter';
import Bootstrap4RowFilteringCell from 'ember-models-table/components/models-table/themes/bootstrap4/row-filtering-cell';
import DefaultCell from 'ember-models-table/components/models-table/themes/default/cell';
import DefaultCellColumnSummary from 'ember-models-table/components/models-table/themes/default/cell-column-summary';
import DefaultCellContentDisplay from 'ember-models-table/components/models-table/themes/default/cell-content-display';
import DefaultCellContentEdit from 'ember-models-table/components/models-table/themes/default/cell-content-edit';
import DefaultCellEditToggle from 'ember-models-table/components/models-table/themes/default/cell-edit-toggle';
import DefaultColumnsDropdown from 'ember-models-table/components/models-table/themes/default/columns-dropdown';
import DefaultColumnsHidden from 'ember-models-table/components/models-table/themes/default/columns-hidden';
import DefaultDataGroupBySelect from 'ember-models-table/components/models-table/themes/default/data-group-by-select';
import DefaultExpandAllToggle from 'ember-models-table/components/models-table/themes/default/expand-all-toggle';
import DefaultExpandToggle from 'ember-models-table/components/models-table/themes/default/expand-toggle';
import DefaultFooter from 'ember-models-table/components/models-table/themes/default/footer';
import DefaultGlobalFilter from 'ember-models-table/components/models-table/themes/default/global-filter';
import DefaultGroupSummaryRow from 'ember-models-table/components/models-table/themes/default/group-summary-row';
import DefaultGroupedHeader from 'ember-models-table/components/models-table/themes/default/grouped-header';
import DefaultNoData from 'ember-models-table/components/models-table/themes/default/no-data';
import DefaultPageSizeSelect from 'ember-models-table/components/models-table/themes/default/page-size-select';
import DefaultPaginationNumeric from 'ember-models-table/components/models-table/themes/default/pagination-numeric';
import DefaultPaginationSimple from 'ember-models-table/components/models-table/themes/default/pagination-simple';
import DefaultRow from 'ember-models-table/components/models-table/themes/default/row';
import DefaultRowExpand from 'ember-models-table/components/models-table/themes/default/row-expand';
import DefaultRowFiltering from 'ember-models-table/components/models-table/themes/default/row-filtering';
import DefaultRowFilteringCell from 'ember-models-table/components/models-table/themes/default/row-filtering-cell';
import DefaultRowGroupToggle from 'ember-models-table/components/models-table/themes/default/row-group-toggle';
import DefaultRowGrouping from 'ember-models-table/components/models-table/themes/default/row-grouping';
import DefaultRowSelectAllCheckbox from 'ember-models-table/components/models-table/themes/default/row-select-all-checkbox';
import DefaultRowSelectCheckbox from 'ember-models-table/components/models-table/themes/default/row-select-checkbox';
import DefaultRowSorting from 'ember-models-table/components/models-table/themes/default/row-sorting';
import DefaultRowSortingCell from 'ember-models-table/components/models-table/themes/default/row-sorting-cell';
import DefaultSelect from 'ember-models-table/components/models-table/themes/default/select';
import DefaultSummary from 'ember-models-table/components/models-table/themes/default/summary';
import DefaultTable from 'ember-models-table/components/models-table/themes/default/table';
import DefaultTableBody from 'ember-models-table/components/models-table/themes/default/table-body';
import DefaultTableFooter from 'ember-models-table/components/models-table/themes/default/table-footer';
import DefaultTableHeader from 'ember-models-table/components/models-table/themes/default/table-header';

export default interface Registry {
  ModelsTable: typeof ModelsTableComponent;
  'models-table': typeof ModelsTableComponent;
  ModelsTableServerPaginated: typeof ModelsTableServerPaginated;
  'models-table-server-paginated': typeof ModelsTableServerPaginated;

  'ModelsTable::Themes::Bootstrap3::RowFilteringCell': typeof Bootstrap3RowSelectAllCheckbox;
  'models-table/themes/bootstrap3/row-filtering-cell': typeof Bootstrap3RowSelectAllCheckbox;

  'ModelsTable::Themes::Bootstrap4::ColumnsDropdown': typeof Bootstrap4ColumnsDropdown;
  'models-table/themes/bootstrap4/columns-dropdown': typeof Bootstrap4ColumnsDropdown;
  'ModelsTable::Themes::Bootstrap4::DataGroupBySelect': typeof Bootstrap4DataGroupBySelect;
  'models-table/themes/bootstrap4/data-group-by-select': typeof Bootstrap4DataGroupBySelect;
  'ModelsTable::Themes::Bootstrap4::GlobalFilter': typeof Bootstrap4GlobalFilter;
  'models-table/themes/bootstrap4/global-filter': typeof Bootstrap4GlobalFilter;
  'ModelsTable::Themes::Bootstrap4::RowFilteringCell': typeof Bootstrap4RowFilteringCell;
  'models-table/themes/bootstrap4/row-filtering-cell': typeof Bootstrap4RowFilteringCell;

  'ModelsTable::Themes::Default::Cell': typeof DefaultCell;
  'models-table/themes/default/cell': typeof DefaultCell;
  'ModelsTable::Themes::Default::CellColumnSummary': typeof DefaultCellColumnSummary;
  'models-table/themes/default/cell-column-summary': typeof DefaultCellColumnSummary;
  'ModelsTable::Themes::Default::CellContentDisplay': typeof DefaultCellContentDisplay;
  'models-table/themes/default/cell-content-display': typeof DefaultCellContentDisplay;
  'ModelsTable::Themes::Default::CellContentEdit': typeof DefaultCellContentEdit;
  'models-table/themes/default/cell-content-edit': typeof DefaultCellContentEdit;
  'ModelsTable::Themes::Default::CellEditToggle': typeof DefaultCellEditToggle;
  'models-table/themes/default/cell-edit-toggle': typeof DefaultCellEditToggle;
  'ModelsTable::Themes::Default::ColumnsDropdown': typeof DefaultColumnsDropdown;
  'models-table/themes/default/columns-dropdown': typeof DefaultColumnsDropdown;
  'ModelsTable::Themes::Default::ColumnsHidden': typeof DefaultColumnsHidden;
  'models-table/themes/default/columns-hidden': typeof DefaultColumnsHidden;
  'ModelsTable::Themes::Default::DataGroupBySelect': typeof DefaultDataGroupBySelect;
  'models-table/themes/default/data-group-by-select': typeof DefaultDataGroupBySelect;
  'ModelsTable::Themes::Default::ExpandAllToggle': typeof DefaultExpandAllToggle;
  'models-table/themes/default/expand-all-toggle': typeof DefaultExpandAllToggle;
  'ModelsTable::Themes::Default::ExpandToggle': typeof DefaultExpandToggle;
  'models-table/themes/default/expand-toggle': typeof DefaultExpandToggle;
  'ModelsTable::Themes::Default::Footer': typeof DefaultFooter;
  'models-table/themes/default/footer': typeof DefaultFooter;
  'ModelsTable::Themes::Default::GlobalFilter': typeof DefaultGlobalFilter;
  'models-table/themes/default/global-filter': typeof DefaultGlobalFilter;
  'ModelsTable::Themes::Default::GroupSummaryRow': typeof DefaultGroupSummaryRow;
  'models-table/themes/default/group-summary-row': typeof DefaultGroupSummaryRow;
  'ModelsTable::Themes::Default::GroupedHeader': typeof DefaultGroupedHeader;
  'models-table/themes/default/grouped-header': typeof DefaultGroupedHeader;
  'ModelsTable::Themes::Default::NoData': typeof DefaultNoData;
  'models-table/themes/default/no-data': typeof DefaultNoData;
  'ModelsTable::Themes::Default::PageSizeSelect': typeof DefaultPageSizeSelect;
  'models-table/themes/default/page-size-select': typeof DefaultPageSizeSelect;
  'ModelsTable::Themes::Default::PaginationNumeric': typeof DefaultPaginationNumeric;
  'models-table/themes/default/pagination-numeric': typeof DefaultPaginationNumeric;
  'ModelsTable::Themes::Default::PaginationSimple': typeof DefaultPaginationSimple;
  'models-table/themes/default/pagination-simple': typeof DefaultPaginationSimple;
  'ModelsTable::Themes::Default::Row': typeof DefaultRow;
  'models-table/themes/default/row': typeof DefaultRow;
  'ModelsTable::Themes::Default::RowExpand': typeof DefaultRowExpand;
  'models-table/themes/default/row-expand': typeof DefaultRowExpand;
  'ModelsTable::Themes::Default::RowFiltering': typeof DefaultRowFiltering;
  'models-table/themes/default/row-filtering': typeof DefaultRowFiltering;
  'ModelsTable::Themes::Default::RowFilteringCell': typeof DefaultRowFilteringCell;
  'models-table/themes/default/row-filtering-cell': typeof DefaultRowFilteringCell;
  'ModelsTable::Themes::Default::RowGroupToggle': typeof DefaultRowGroupToggle;
  'models-table/themes/default/row-group-toggle': typeof DefaultRowGroupToggle;
  'ModelsTable::Themes::Default::RowGrouping': typeof DefaultRowGrouping;
  'models-table/themes/default/row-grouping': typeof DefaultRowGrouping;
  'ModelsTable::Themes::Default::RowSelectAllCheckbox': typeof DefaultRowSelectAllCheckbox;
  'models-table/themes/default/row-select-all-checkbox': typeof DefaultRowSelectAllCheckbox;
  'ModelsTable::Themes::Default::RowSelectCheckbox': typeof DefaultRowSelectCheckbox;
  'models-table/themes/default/row-select-checkbox': typeof DefaultRowSelectCheckbox;
  'ModelsTable::Themes::Default::RowSorting': typeof DefaultRowSorting;
  'models-table/themes/default/row-sorting': typeof DefaultRowSorting;
  'ModelsTable::Themes::Default::RowSortingCell': typeof DefaultRowSortingCell;
  'models-table/themes/default/row-sorting-cell': typeof DefaultRowSortingCell;
  'ModelsTable::Themes::Default::Select': typeof DefaultSelect;
  'models-table/themes/default/select': typeof DefaultSelect;
  'ModelsTable::Themes::Default::Summary': typeof DefaultSummary;
  'models-table/themes/default/summary': typeof DefaultSummary;
  'ModelsTable::Themes::Default::Table': typeof DefaultTable;
  'models-table/themes/default/table': typeof DefaultTable;
  'ModelsTable::Themes::Default::TableBody': typeof DefaultTableBody;
  'models-table/themes/default/table-body': typeof DefaultTableBody;
  'ModelsTable::Themes::Default::TableFooter': typeof DefaultTableFooter;
  'models-table/themes/default/table-footer': typeof DefaultTableFooter;
  'ModelsTable::Themes::Default::TableHeader': typeof DefaultTableHeader;
  'models-table/themes/default/table-header': typeof DefaultTableHeader;

  'ModelsTable::Themes::PlainHtml::ColumnsDropdown': typeof PlainHtmlColumnsDropdown;
  'models-table/themes/plain-html/columns-dropdown': typeof PlainHtmlColumnsDropdown;
  'ModelsTable::Themes::PlainHtml::GlobalFilter': typeof PlaintHtmlGlobalFilter;
  'models-table/themes/plain-html/global-filter': typeof PlaintHtmlGlobalFilter;
  'ModelsTable::Themes::PlainHtml::RowFilteringCell': typeof PlainHtmlRowFilteringCell;
  'models-table/themes/plain-html/row-filtering-cell': typeof PlainHtmlRowFilteringCell;
  'ModelsTable::Themes::PlainHtml::Summary': typeof PlainHtmlSummary;
  'models-table/themes/plain-html/summary': typeof PlainHtmlSummary;

  'ModelsTable::Themes::EmberBootstrapV4::ColumnsDropdown': typeof EmberBootstrapV4ColumnsDropdown;
  'models-table/themes/ember-bootstrap-v4/columns-dropdown': typeof EmberBootstrapV4ColumnsDropdown;
  'ModelsTable::Themes::EmberBootstrapV4::DataGroupBySelect': typeof EmberBootstrapV4DataGroupBySelect;
  'models-table/themes/ember-bootstrap-v4/data-group-by-select': typeof EmberBootstrapV4DataGroupBySelect;
  'ModelsTable::Themes::EmberBootstrapV4::GlobalFilter': typeof EmberBootstrapV4GlobalFilter;
  'models-table/themes/ember-bootstrap-v4/global-filter': typeof EmberBootstrapV4GlobalFilter;
  'ModelsTable::Themes::EmberBootstrapV4::RowFilteringCell': typeof EmberBootstrapV4RowFilteringCell;
  'models-table/themes/ember-bootstrap-v4/row-filtering-cell': typeof EmberBootstrapV4RowFilteringCell;
  'ModelsTable::Themes::EmberBootstrapV4::Summary': typeof EmberBootstrapV4Summary;
  'models-table/themes/ember-bootstrap-v4/summary': typeof EmberBootstrapV4Summary;

  'ModelsTable::Themes::EmberBootstrapV5::ColumnsDropdown': typeof EmberBootstrapV5ColumnsDropdown;
  'models-table/themes/ember-bootstrap-v5/columns-dropdown': typeof EmberBootstrapV5ColumnsDropdown;
  'ModelsTable::Themes::EmberBootstrapV5::DataGroupBySelect': typeof EmberBootstrapV5DataGroupBySelect;
  'models-table/themes/ember-bootstrap-v5/data-group-by-select': typeof EmberBootstrapV5DataGroupBySelect;
  'ModelsTable::Themes::EmberBootstrapV5::GlobalFilter': typeof EmberBootstrapV5GlobalFilter;
  'models-table/themes/ember-bootstrap-v5/global-filter': typeof EmberBootstrapV5GlobalFilter;
  'ModelsTable::Themes::EmberBootstrapV5::PageSizeSelect': typeof EmberBootstrapV5PageSizeSelect;
  'models-table/themes/ember-bootstrap-v5/page-size-select': typeof EmberBootstrapV5PageSizeSelect;
  'ModelsTable::Themes::EmberBootstrapV5::PaginationNumeric': typeof EmberBootstrapV5PaginationNumeric;
  'models-table/themes/ember-bootstrap-v5/pagination-numeric': typeof EmberBootstrapV5PaginationNumeric;
  'ModelsTable::Themes::EmberBootstrapV5::PaginationSimple': typeof EmberBootstrapV5PaginationSimple;
  'models-table/themes/ember-bootstrap-v5/pagination-simple': typeof EmberBootstrapV5PaginationSimple;
  'ModelsTable::Themes::EmberBootstrapV5::RowFilteringCell': typeof EmberBootstrapV5RowFilteringCell;
  'models-table/themes/ember-bootstrap-v5/row-filtering-cell': typeof EmberBootstrapV5RowFilteringCell;
  'ModelsTable::Themes::EmberBootstrapV5::Summary': typeof EmberBootstrapV5Summary;
  'models-table/themes/ember-bootstrap-v5/summary': typeof EmberBootstrapV5Summary;
}
